NCAR/obs2ioda

obs2ioda-v2/src/Makefile
obs2ioda-v2/src/define_mod.f90
obs2ioda-v2/src/hsd.f90
obs2ioda-v2/src/ncio_mod.f90

**Description**
This PR fixes some bugs found to convert raw AHI observations from the AWS cloud in Himawari Standard Data (HSD) format to the IODA-v2 needed in `mpas-jedi`. It was added the capability to read files with segment number 01, which corresponds to the no segment division of HSD data. The reading of the variables was modified to read each one explicitly since otherwise it was not working properly (not sure why). Specifically the way the variable `idata`, which is the count (total number of pixels that results from multiplying the number of columns by the number of lines) needed for the radiance calculation is also modified. This modification results in the correct calculation of the radiance and then the brightness temperature. In addition, the variable for the `dateTime` in …

Fix bugs to convert raw AHI observations from AWS in HSD format to IODA-v2

---

goes_abi/src/Makefile
obs2ioda-v2/src/hsd.f90
obs2ioda-v2/src/main.f90

This PR adds the superobbing capability for AHI observations. Giving the half width of the superobbing grid as an entry parameter, the code computes the average brightness temperature in the box defined using that parameter. This code is adapted from https://github.com/wrf-model/WRF/blob/develop/var/da/da_radiance/da_read_obs_netcdf4ahi_jaxa.inc and follows the same implementation as for ABI observations from GOES-16. The debugging build flags for the goes_abi code are removed. The following figures show the brightness temperature results for AHI observations after using this converter for 2018-04-15T00 channel 8 (a) without superobbing and  (b) with superobbing on a grid of 59x59 pixels:
**a)**
**b)**
**Issue closed**
Closes https://github.com/NCAR/obs2ioda/issues/1

Add superobbing capability for AHI observations

---

.gitignore
obs2ioda-v1/README.md
obs2ioda-v2/README.md

This PR modifies the documentation on converting the HSD file using obs2ioda. Default value for pixel to skip (option -s) has been changed from 3 to 1 which means no pixel will be skipped. 
Modified Files: 
M obs2ioda-v1/README.md
M obs2ioda-v2/README.md

Modified documentation on converting HSD files

---

CMakeLists.txt
cmake/Functions/Obs2Ioda_Functions.cmake
cmake/Modules/FindNetCDF.cmake
obs2ioda-v2/CMakeLists.txt
obs2ioda-v2/README.md
obs2ioda-v2/src/hsd.f90

**TYPE**: enhancement
**KEYWORDS**: cmake, build system, compiler compatibility
**DESCRIPTION OF CHANGES**:  
**Problem**:  
The `obs2ioda-v2` library lacked support for CMake-based builds, which complicated the build process across different platforms and made compiler compatibility (GNU and Intel) more difficult to manage.
**Solution**:  
- Added support for building `obs2ioda-v2` using CMake, leveraging the modern build system to streamline cross-platform integration.
- Updated the `obs2ioda-v2` README with instructions on how to build the library using CMake and provided additional guidance for building the NCEP BUFR library.
- Fixed a boolean equality check in `hsd.f90` to ensure `obs2ioda-v2` compiles successfully on both GNU and Intel compilers.
These changes improve the ease of …

Feature: CMake Build Support for obs2ioda-v2

---

cmake/Functions/Obs2Ioda_Functions.cmake
obs2ioda-v2/src/hsd.f90

**Description**
---
This PR addresses a critical issue where the iloc variable was not initialized in the read_HSD subroutine within ahi_HSD_mod. This uninitialized variable led to out-of-bounds memory access and incorrect calculations, particularly when parsing AHI files without superobbing.
**Summary of Changes**
---
Bug Fix: iloc variable initialization.
The iloc counter, which tracks the data point location during AHI file parsing, is now initialized to 0 at the start of the parsing loop. This prevents segmentation faults that were occurring due to uninitialized memory access and inaccurate data handling.
Specifically, this change ensures that the code does not attempt to access invalid memory or overwrite values in the output arrays, resulting in more accurate parsing and allocation …

Fix Segmentation Fault and Memory Access Issues in AHI File Parsing by Initializing iloc

---

obs2ioda-v2/src/ncio_mod.f90

The original code in `ncio_mod.f90` encountered an out-of-bounds error with bounds checking enabled, primarily due to the following reasons:
1. **Out-of-Bounds Access**: The code attempted to access `geoinst_list(ityp)` where `ityp` often exceeded the bounds of `geoinst_list`, causing a runtime error when bounds checking was enabled in gfortran.
2. **Convoluted Logic**: The condition for selecting the `set_obserr` subroutine relied on checking if `geoinst_list(ityp)` equaled `"ahi_himawari8"`. However, this was indirect and unreliable, as the true condition of interest was whether `write_opt == write_nc_radiance_geo`.
The logic was refactored to directly check `if (write_opt == write_nc_radiance_geo)`, ensuring the proper subroutine (`set_ahi_obserr` or `set_brit_obserr`) is selected …

Fix Out-of-Bounds Error and Streamline Logic for Setting Observation Error Subroutine in ncio_mod.f90

---

cmake/Obs2Ioda_Functions.cmake

**Summary**
This PR introduces a new CMake function, obs2ioda_cxx_library, to simplify and standardize the configuration of obs2ioda C++ library targets.
**Function Overview**
The obs2ioda_cxx_library function takes a single argument, target, representing the C++ target to configure. It performs the following key actions:
* Sets the INSTALL_RPATH property to ensure that shared libraries can be found relative to the target's installation directory.
* Retrieves public link libraries by dynamically constructing the variable name ${target}_PUBLIC_LINK_LIBRARIES.
* Links the retrieved libraries to the target using target_link_libraries.
* This setup ensures proper linkage and runtime configuration for relocatable installations.
**Benefits**
* Improved Modularity: Centralizes and simplifies the …

Add obs2ioda_cxx_library CMake Function for Configuring C++ Libraries

---

cmake/Obs2Ioda_Functions.cmake
obs2ioda-v2/CMakeLists.txt

This PR refactors the `obs2ioda_fortran_target` CMake function by splitting its functionality into two separate functions:  
- `obs2ioda_fortran_library`  
- `obs2ioda_fortran_executable`  
Previously, the `obs2ioda_fortran_target` function served two purposes:  
1. Configuring a Fortran library by setting target properties.  
2. Creating a corresponding executable.  
This coupling meant the function could only be used when both a Fortran library **and** a corresponding executable were required. It was not possible to configure a standalone Fortran library without also creating an executable, limiting its flexibility.
- Introduced `obs2ioda_fortran_library` to handle the creation and configuration of standalone Fortran libraries.  
- Introduced `obs2ioda_fortran_executable` to handle the …

Split `obs2ioda_fortran_target` into `obs2ioda_fortran_library` and `obs2ioda_fortran_executable`  

---

CMakeLists.txt
cmake/Obs2Ioda_Functions.cmake
obs2ioda-v2/CMakeLists.txt
obs2ioda-v2/src/cxx/CMakeLists.txt
obs2ioda-v2/src/cxx/netcdf_error.cc
obs2ioda-v2/src/cxx/netcdf_error.h

Updated PR Description
Summary
This PR introduces the netcdfErrorMessage function to improve NetCDF C++ exception handling in the Obs2Ioda namespace.
Changes Made
•	Implemented netcdfErrorMessage in netcdf_error.h and netcdf_error.cpp.
•	The function accepts a netCDF::exceptions::NcException object, a line number, and a file name as input.
•	It formats and prints detailed error messages, including the error code, file name, and line number (if provided), to standard error.
Benefits
•	Provides more informative and consistent error reporting for NetCDF exceptions.
•	Simplifies exception handling by consolidating error message construction and logging into a reusable function.
•	Enhances debugging by including file name and line number in the error message.
Example Usage
#include …

Add `netcdfErrorMessage` Function for Handling NetCDF C++ Exceptions

---

CMakeLists.txt
obs2ioda-v2/CMakeLists.txt
obs2ioda-v2/src/cxx/CMakeLists.txt
obs2ioda-v2/src/cxx/netcdf_file.cc
obs2ioda-v2/src/cxx/netcdf_file.h
obs2ioda-v2/src/netcdf_cxx_i_mod.f90
obs2ioda-v2/src/netcdf_cxx_mod.f90

**Description:**
- This PR introduces a Fortran interface for creating and closing NetCDF files using the NetCDF C++ API. The new implementation emphasizes thread safety, robust error handling, and user-friendly interactions. Below are the key highlights:
- Thread-Safe Operations: All file operations are implemented in a thread-safe manner. It should be noted that NetCDF itself is not guarenteed to be thread safe.
- Robust Error Handling: Utilizes the rich NetCDF C++ Exception class to handle errors gracefully and provide detailed diagnostic information when issues occur.
**User-Friendly Fortran Interface:**
- Abstracts away the complexities of Fortran/C type casting.
- Handles all memory management and memory transfers, allowing users to focus on their core logic without worrying about …

Add  Fortran Interface for NetCDF File Operations Using C++ API

---

obs2ioda-v2/src/gnssro_mod.f90

This PR fixes a satellite ID bug in subroutine bendingangle_err_gsi. Previously, the module defined a global variable said and a local variable said in subroutine read_write_gnssro. The local variable was initialized in read_write_gnssro, while the global variable remained uninitialized. Subroutine bengingangle_err_gsi incorrectly used the uninitialized global variable instead of the local one, which made the said comparisons meaningless. This PR removes the global variable and passes the local variable to bendingangle_err_gsi.
Ran example BUFR file conversion and verified that the said passed to bendingangle_err_gsi is nonzero.

Fix satellite ID bug in gnssro_module

---

obs2ioda-v2/src/cxx/CMakeLists.txt
obs2ioda-v2/src/cxx/netcdf_dimension.cc
obs2ioda-v2/src/cxx/netcdf_dimension.h
obs2ioda-v2/src/netcdf_cxx_i_mod.f90
obs2ioda-v2/src/netcdf_cxx_mod.f90

This PR introduces support for adding dimensions to NetCDF files from Fortran using the NetCDF C++ API. The new implementation provides a Fortran interface that simplifies the process of creating dimensions, including global dimensions and group-specific dimensions, by handling all necessary memory management and C/Fortran string conversions.
- **Dimension Creation**:
- Supports creating dimensions in the root group or any specified group.
- **User-Friendly Fortran Interface**:
- Abstracts low-level details by wrapping the C++ API with a Fortran-friendly interface.
- Automatically converts Fortran strings to C-compatible null-terminated strings.
- Handles optional arguments for specifying the target group.
This enhancement allows Fortran users to leverage the powerful capabilities of the …

Add Fortran Support for Creating Dimensions in NetCDF Files Using C++ API

---

obs2ioda-v2/src/netcdf_cxx_mod.f90

An import statement was missing in netcdf_cxx_mod, which lead to an error when compiling the code in our current main branch. This PR fixes the bug.
TYPE: bug fix
TESTS CONDUCTED: successfully compiled code with mpas-jedi gnu environment.

Import missing interface in netcdf_cxx_mod required for compilation.

---

obs2ioda-v2/src/cxx/CMakeLists.txt
obs2ioda-v2/src/cxx/netcdf_variable.cc
obs2ioda-v2/src/cxx/netcdf_variable.h
obs2ioda-v2/src/netcdf_cxx_i_mod.f90
obs2ioda-v2/src/netcdf_cxx_mod.f90

This PR adds support for creating and writing variables in NetCDF files from Fortran using the NetCDF C++ API. It simplifies defining variables, specifying data types and dimensions, and writing data, handling both global and group-specific variables.
- **Variable Creation:** Supports defining variables with multiple dimensions in global or group contexts.
- **Data Writing:** Enables writing integer, real, and string data with automatic C/Fortran string conversion.
- **Fortran-Friendly Interface:** Abstracts low-level C++ API details, ensuring easy integration.
This enhancement provides a streamlined Fortran interface for NetCDF variable management, eliminating manual memory handling and C interoperability complexities.

Support for Creating and Setting NetCDF Variables

---

obs2ioda-v2/src/f_c_string_t_mod.f90

This PR updates the `to_c` type-bound function in the `f_c_string_t` derived type to ensure that the returned C address corresponds to a null-terminated, **trimmed** version of the provided Fortran string. Previously, the function allocated space based on the full Fortran string length, which could lead to trailing whitespace when accessed from C.  
- The function now calculates the **length of the trimmed Fortran string** (`n = len(trim(f_string))`), ensuring no unnecessary trailing spaces are included.  
- Memory is **dynamically allocated** to store the trimmed string with a null terminator (`c_null_char`).  
- The **C address** returned now properly corresponds to the **trimmed** Fortran string.

Ensure `to_c` Returns the C Address of a Trimmed Fortran String  

---

obs2ioda-v2/src/gnssro_mod.f90

TYPE: enhancement
DESCRIPTION OF CHANGES:
This PR splits subroutine read_write_gnssro into multiple subroutines and improves the overall source formatting. The new subroutines correspond approximately to the following line numbers in the current main-branch file version (434c723):
- subroutine get_buffer_information: lines 108 - 135
- subroutine allocate_gnssro_data_array: lines 137 - 156
- subroutine read_gnssro_data: lines 160 - 331
- subroutine write_gnssro_data: lines 333 - 482
- subroutine deallocate_gnssro_data_array: lines 484 - 503
The derived type for gnssro data and commonly used parameters are further defined as module variables. The PR does not attempt to improve the source code inside the subroutines, in part because I am not familiar enough with the details of the GNSSRO …

Refactor gnssro observation processing module

---

obs2ioda-v2/src/cxx/netcdf_dimension.cc
obs2ioda-v2/src/cxx/netcdf_dimension.h
obs2ioda-v2/src/netcdf_cxx_i_mod.f90
obs2ioda-v2/src/netcdf_cxx_mod.f90

This PR updates `netcdfAddDim` to return the newly created dimension ID, allowing it to be easily retrieved in Fortran.  
- Added an `int *dimID` parameter to `netcdfAddDim`.  
- Modified the function to store the dimension ID after calling `addDim()`:  
```cpp
*dimID = dim.getId();
```
- Ensured behavior remains consistent while enabling Fortran compatibility.  
- All tests passed in the dedicated testing branch [testing/netcdfAddDim_dimID_arg](https://github.com/NCAR/obs2ioda/tree/testing/netcdfAddDim_dimID_arg)
- Tests verify `dimID` is set correctly and is incremented by one in fortran.

Update `netcdfAddDim` to Return Dimension ID  

---

obs2ioda-v2/src/netcdf_cxx_mod.f90

**Description:**  
This PR adds an optional argument, `fillValue`, to the `netcdfAddVar` function, allowing users to specify a default fill value when defining a variable. Previously, setting a fill value required calling `netcdfAddVar` followed by `netcdfSetFill`. With this change, users can set the fill value directly in `netcdfAddVar`. If `fillValue` is not provided, the behavior remains unchanged.
**Testing**
All relevant [tests](https://github.com/NCAR/obs2ioda/blob/testing/netcdfAddVar_fillValue_arg/test/fortran/netcdf_variable_test.f90) passed in the [testing branch](https://github.com/NCAR/obs2ioda/tree/testing/netcdfAddVar_fillValue_arg)
**Dependencies**
- Refactor ncio_mod module to use NetCDF C++ wrappers #43 depends on this PR

Add optional `fillValue` argument to `netcdfAddVar` 

---

obs2ioda-v2/src/cxx/netcdf_variable.cc
obs2ioda-v2/src/cxx/netcdf_variable.h
obs2ioda-v2/src/netcdf_cxx_i_mod.f90
obs2ioda-v2/src/netcdf_cxx_mod.f90

This PR adds support for writing **NetCDF double array variables** in the C++ NetCDF interface. This ensures the interface can handle writing double precision data.
- All tests in the **`testing/netcdf_variable_double_arrays`** branch passed.
- No other PRs depend on this PR.

Add support for writing NetCDF double array variables

---

obs2ioda-v2/src/cxx/netcdf_attribute.cc
obs2ioda-v2/src/cxx/netcdf_attribute.h
obs2ioda-v2/src/netcdf_cxx_i_mod.f90
obs2ioda-v2/src/netcdf_cxx_mod.f90

This PR adds support for writing **NetCDF integer array attributes** in the C++ NetCDF interface. This functionality is needed to support processing **GNSSRO BUFR files**, which store key metadata as integer arrays.
---
GNSSRO BUFR files contain critical metadata stored as integer arrays. This PR ensures the new C++ interface can correctly write these attributes, supporting GNSSRO BUFR file conversions.
---
- All tests in the **`testing/netcdf_attribute_integer_arrays`** branch passed.
- Support for processing **GNSSRO BUFR** files depend on this PR.

Add support for writing NetCDF integer array attributes

---

obs2ioda-v2/src/define_mod.f90
obs2ioda-v2/src/gnssro_mod.f90
obs2ioda-v2/src/main.f90

TYPE: enhancement
This PR enables output of hourly (or other intervals as specified in `hour_fgat`) IODA files for GNSSRO observations, analogous to the other observation types. It also updates global attributes to make the file structure more similar to other observations.
USAGE:
Specify the `-split` option to output IODA files every `hour_fgat` instead of every 6h. For example, assuming `hour_fgat = 1`:
```sh
$ ./obs2ioda_v2 -split gdas.gpsro.t00z.20180415.bufr  # generates 1h IODA files
$ ./obs2ioda_v2 gdas.gpsro.t00z.20180415.bufr  # generates 6h IODA file
```
1. Compared 6h IODA file vs. result from main branch. The only differences are in the updated global attributes, as expected:
```sh
$ nccmp -ldmgefs gnssro_obs_2018041500.h5 main/6h/gnssro_obs_2018041500.h5
DIFFER : NUMBER OF …
```

Enable hourly IODA file output for GNSSRO obs

---

obs2ioda-v2/src/cxx/netcdf_attribute.cc
obs2ioda-v2/src/cxx/netcdf_attribute.h
obs2ioda-v2/src/netcdf_cxx_i_mod.f90
obs2ioda-v2/src/netcdf_cxx_mod.f90

TYPE: enhancement
This PR adds the functionality to write single-precision floating point array attributes. This is required to generate GNSSRO IODA files.
Wrote one single-precision floating point array attribute to file and confirmed that it was equivalent to the attribute generated by the fortran netcdf interface.

Add support for single-precision floating point array attributes.

---

CMakeLists.txt
obs2ioda-v2/src/cxx/netcdf_variable.h
obs2ioda-v2/src/ncio_mod.f90

This PR refactors the `ncio_mod` module by replacing direct NetCDF Fortran calls with a NetCDF C++ wrapper. 
- **NetCDF I/O Update**: Replaced all NetCDF Fortran I/O calls with equivalent calls from the NetCDF C++ wrapper (`netcdf_cxx`).  
This PR depends on the following PRs:  
- **[[#46: Add Support for Writing NetCDF Character Arrays from Fortran via C++ Wrapper](https://github.com/NCAR/obs2ioda/pull/46)](https://github.com/NCAR/obs2ioda/pull/46)**  
- Required for `netcdfAddDim` to properly set `dimID`.  
- Also necessary to support writing `char` arrays, ensuring that NetCDF files produced by the new C++ interface are **bitwise identical** to those generated by the original Fortran implementation.  
- **[[#47: Update netcdfAddDim to Return Dimension …

Refactor ncio_mod module to use NetCDF C++ wrappers

---

obs2ioda-v2/src/gnssro_mod.f90

TYPE: enhancement
This PR migrates the IODA file output from the old Fortran to the new C++ NetCDF interface. The resulting IODA file is identical to the one generated with the old interface.
1. Compared 6h IODA file output to result from main branch (labeled ref below):
```sh
$ nccmp -ldmgefs gnssro_obs_2018041500.h5 ref/6h/gnssro_obs_2018041500.h5
Files "gnssro_obs_2018041500.h5" and "ref/6h/gnssro_obs_2018041500.h5" are identical.
```
2. Successfully ran a short 3dEnVar DA with observations processed with the updated converter.

Use new C++ NetCDF interface in GNSSRO obs converter

---

obs2ioda-v2/src/ncio_mod.f90

This PR updates the scan position variable type from `float` to `int` to ensure compliance with the IODA v2 format.  
- Modified the scan position variable type from `float` to `int`.  
- IODA v2 requires scan position to be stored as an integer rather than a floating-point value.

Change Scan Position Variable Type from Float to Int for IODA v2 Compliance

---

cmake/Obs2Ioda_CompilerFlags.cmake
cmake/Obs2Ioda_Functions.cmake

This PR moves `-mcmodel=medium` into a separate compiler flag list that is only added when using GNU compilers on Linux. This allows the library to compile on macOS with GNU compilers, which previously failed due to `-mcmodel` being a Linux-specific flag.

Make `-mcmodel=medium` GNU/Linux-Specific to Support macOS Compilation

---

obs2ioda-v2/src/netcdf_cxx_mod.f90

This PR updates `netcdf_cxx_mod` to ensure Fortran standard compliance and resolve compilation failures with Intel compilers.
Throughout `netcdf_cxx_mod`, variables passed to the Fortran intrinsic `c_loc` were **not declared with the `target` attribute**, which is a requirement of the Fortran standard. While GNU compilers allow this non-compliant usage, Intel compilers correctly raise errors, causing the build to fail when using `ifort` or `ifx`.
All variables passed to `c_loc` in `netcdf_cxx_mod` have been updated to include the `target` attribute. This ensures the code conforms to the Fortran standard and is portable across multiple compiler suites.
- No changes to logic or behavior — purely a fix to variable declarations
- Fix confirmed with both GNU and Intel compiler toolchains

Fix Intel compilation error due to non-standard `c_loc` usage

---

CMakeLists.txt
obs2ioda-v2/src/cxx/CMakeLists.txt

This PR integrates `yaml-cpp` into the CMake build system using `FetchContent`. This allows `yaml-cpp` to be automatically downloaded and built as part of the project's build process, eliminating the need for external installations.

Add yaml-cpp as a Dependency via CMake FetchContent

---

obs2ioda-v2/src/gnssro_mod.f90

This PR updates the `write_gnssro_data` subroutine to write a global `Location` dimension variable.
- Added a call to `netcdfAddVar` to define a global variable for the `Location` dimension in `gnssro` output files.
The latest IODA format requires an explicit global variable for each dimension, including `Location`. This update ensures that `gnssro` files written by this module remain compatible with the latest version of `IODA`.

Add global Location dimension variable to `write_gnssro_data` subroutine

---

CMakeLists.txt
config/CMakeLists.txt
config/FilePathConfig.h.in
obs2ioda-v2/src/cxx/CMakeLists.txt
obs2ioda-v2/src/cxx/ioda_obs_schema.cc
obs2ioda-v2/src/cxx/ioda_obs_schema.h
obs2ioda-v2/src/cxx/netcdf_attribute.cc
obs2ioda-v2/src/cxx/netcdf_dimension.cc
obs2ioda-v2/src/cxx/netcdf_file.cc
obs2ioda-v2/src/cxx/netcdf_file.h
obs2ioda-v2/src/cxx/netcdf_group.cc
obs2ioda-v2/src/cxx/netcdf_variable.cc
share/ObsSpace.yaml
test/CMakeLists.txt
test/cxx/CMakeLists.txt
test/cxx/fixture/IodaObsSchemaFixture.cc
test/cxx/fixture/IodaObsSchemaFixture.h
test/cxx/test_IodaObsSchema.cc

This PR introduces the `IodaSchema` class, which parses the `ObsSpace.yaml` IODA format validation file and validates `obs2ioda`-generated NetCDF output files against the latest IODA naming and formatting conventions.
- **Schema-Based Validation:**  
Ensures that `obs2ioda` output remains compliant with evolving IODA format standards by using a centralized schema for validation.
- **Non-Invasive Integration:**  
Allows `obs2ioda` to continue using its existing I/O logic, while validating the resulting files post hoc, avoiding the need for frequent updates to output logic.
- **Future-Proof Design:**  
The schema is modular and extensible—each core schema component (`Variable`, `Attribute`, `Dimension`, and `Group`) is implemented as its own class to support future IODA format changes and …

Add `IodaObsSchema` Class for Validating `obs2ioda` NetCDF Output

---

README.md
cmake/Obs2Ioda_Test_Functions.cmake
env-setup/environment.yml
env-setup/gnu_derecho.csh
env-setup/gnu_derecho.sh
env-setup/intel_derecho.csh
env-setup/intel_derecho.sh
src/goes_abi_converter.f90
src/goes_abi_converter_mod.f90
src/utils_mod.f90
test/fortran/CMakeLists.txt
test/fortran/set_goes_abi_out_fname.test.f90
test/fortran/to_lower.test.f90
test/validation/CMakeLists.txt

This PR updates the `goes_abi` converter in the `obs2ioda` library to improve compliance with the IODA v3 format and address several compilation issues.
* **Corrected `dateTime` representation**:
The `dateTime` variable is now written as an `int64` array representing epoch seconds for each observation, instead of as a string. This aligns with the expected format for IODA v3 files.
* **Added `dateTime` units attribute**:
The NetCDF attribute for `dateTime` units was added (`"seconds since 1970-01-01T00:00:00Z"`), as required by the IODA v3 specification.
* **Compilation fixes**:
Resolved various minor compilation issues, including Fortran unit tests that previously failed to compile with the Intel Fortran compiler.
* **Simplified output file naming:**
The output file name now includes only …

Update `datetime` handling to use `dateTime` with correct type and fill behavior and simplify environment setup
